backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Path", name: "path", widgeth: "hidden", default: "/"}
          - label: "Hero Content"
            name: "heroContent"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Subheader", name: "subheader", widget: "string"}
              - label: "Summaries"
                name: "summaries"
                widget: "list"
                allow_add: true
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }

          - label: "Work Examples"
            name: "workExamples"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "img", widget: "image" }

          - label: "Project Archive"
            name: "projectArchive"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Dates", name: "dateDescription", widget: "string"}
              - {label: "Subheader", name: "subheader", widget: "string"}
              - label: "Projects"
                name: "projects"
                widget: "list"
                allow_add: true
                fields:
                  - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Image", name: "image", widget: "image" }

          - label: "Contact Section"
            name: "contact"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Call to Action", name: "cta", widget: "text" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Copy Email Text", name: "copyEmailText", widget: "string" }

      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about/"}
          - label: "Intro Section"
            name: "intro"
            widget: "object"
            fields:
              - { label: "Header", name: "header", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Image alt text", name: "alt", widget: "string" }
          - label: "Moments of Work"
            name: "work"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", default: "Moments of Work" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Recognition Section"
                name: "recognition"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Recognitions"
                    name: "recognitions"
                    widget: "list"
                    fields:
                      - { label: "Award Name/Description", name: "award", widget: "string" }
              - label: "Timeline"
                name: "timeline"
                widget: "list"
                fields:
                  - { label: "Company", name: "company", widget: "string" }
                  - { label: "Role", name: "role", widget: "string" }
                  - { label: "Dates Involved", name: "dates", widget: "string" }
          - label: "Moments of Play"
            name: "play"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", default: "Moments of Play" }
              - label: "Categories of Play"
                name: "categories"
                widget: "list"
                fields:
                  - { label: "Category", name: "category", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - label: "Activities"
                    name: "activities"
                    widget: "list"
                    field:
                      { label: "Activity", name: "activity", widget: "string" }
                  - label: "Collage"
                    name: "image"
                    widget: "image"

  - label: "Components"
    name: "components"
    files:
      - file: "src/info/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Data Key", name: "dataKey", widget: "hidden", default: "footer"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Link Groups"
            name: "linkGroups"
            widget: "list"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
      - file: "src/info/header.md"
        label: "Header"
        name: "header"
        fields:
          - {label: "Data Key", name: "dataKey", widget: "hidden", default: "header"}
          - {label: "Site Title", name: "siteTitle", widget: "string", default: "Jeff Wang"}
          - label: "Navigation Links"
            name: "navigation"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Pathname", name: "pathname", widget: "string"}
  - label: "Other Information"
    name: "info"
    files:
      - file: "src/info/general-info.md"
        label: "General Information"
        name: "general"
        fields:
          - {label: "Data Key", name: "dataKey", widget: "hidden", default: "general-info"}
          - {label: "Email", name: "email", widget: "string"}
