backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Path", name: "path", widgeth: "hidden", default: "/"}
          - label: "Hero Content"
            name: "heroContent"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Subheader", name: "subheader", widget: "string"}
              - label: "Summaries"
                name: "summaries"
                widget: "list"
                allow_add: true
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }

          - label: "Work Examples"
            name: "workExamples"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Image", name: "img", widget: "image" }

          - label: "Project Archive"
            name: "projectArchive"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Dates", name: "dateDescription", widget: "string"}
              - {label: "Subheader", name: "subheader", widget: "string"}
              - label: "Projects"
                name: "projects"
                widget: "list"
                allow_add: true
                fields:
                  - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
                  - { label: "Image", name: "img", widget: "image" }

          - label: "Contact Section"
            name: "contact"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Call to Action", name: "cta", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Copy Email Text", name: "copyEmailText", widget: "string" }

      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - label: "Components"
    name: "components"
    files:
      - file: "src/components/footer/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Link Groups"
            name: "linkGroups"
            widget: "list"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
